icons:
  on: false
  custom:
    play: "â–¶"
    pause: "â¸"
    next: "â­"
    previous: "â®"
    shuffle: "ğŸ”€"
    repeat: "ğŸ”"
    repeat_once: "ğŸ”‚"

keymaps:
  n: next
  p: previous
  h: left
  l: right
  j: down
  k: up
  d: select_device
  q: exit
  "ctrl+s": toggle_shuffle
  "ctrl+r": toggle_repeat
  "?": help
  space: toggle_playback
  +: volume_up
  "-": volume_down
